baseURL = ''
languageCode = 'en-us'
title = 'Kye Gregory | Portfolio'

[params]
  favicon = "images/favicon.ico"

[module]
    [[module.imports]]
        path = 'github.com/kye-gregory/hugo-portfolio-markdown'
